# Form implementation generated from reading ui file 'c:\Users\jave_\OneDrive\Documentos\UPIITA\Prog Avanzada\Conecct_2\Conecct\ConectarServidor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 168)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.label.setStyleSheet("font: 700 italic 10pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.nombre = QtWidgets.QLineEdit(parent=Dialog)
        self.nombre.setGeometry(QtCore.QRect(160, 20, 201, 21))
        self.nombre.setObjectName("nombre")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_2.setStyleSheet("font: 700 italic 10pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.servidor = QtWidgets.QLineEdit(parent=Dialog)
        self.servidor.setGeometry(QtCore.QRect(90, 70, 113, 21))
        self.servidor.setObjectName("servidor")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.label_3.setStyleSheet("font: 700 italic 10pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.puerto = QtWidgets.QLineEdit(parent=Dialog)
        self.puerto.setGeometry(QtCore.QRect(80, 120, 113, 21))
        self.puerto.setObjectName("puerto")
        self.conectar = QtWidgets.QPushButton(parent=Dialog)
        self.conectar.setGeometry(QtCore.QRect(290, 120, 111, 41))
        self.conectar.setObjectName("conectar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "NOMBRE DE USUARIO:"))
        self.label_2.setText(_translate("Dialog", "SERVIDOR:"))
        self.label_3.setText(_translate("Dialog", "PUERTO:"))
        self.conectar.setText(_translate("Dialog", "CONECTAR"))
