# Form implementation generated from reading ui file 'c:\Users\jave_\OneDrive\Documentos\UPIITA\Prog Avanzada\Conecct_2\Conecct\Jugar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog1(object):
    def setupUi(self, Dialog1):
        Dialog1.setObjectName("Dialog1")
        Dialog1.resize(582, 418)
        Dialog1.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label_2 = QtWidgets.QLabel(parent=Dialog1)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 211, 61))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setStyleSheet("font: 18pt \"Segoe UI\";\n"
"background-color: rgb(255, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.msg = QtWidgets.QLabel(parent=Dialog1)
        self.msg.setGeometry(QtCore.QRect(200, 100, 371, 291))
        self.msg.setStyleSheet("font: 700 italic 14pt \"Segoe UI\";\n"
"background-color: rgb(85, 170, 255);")
        self.msg.setObjectName("msg")
        self.onkin = QtWidgets.QPushButton(parent=Dialog1)
        self.onkin.setGeometry(QtCore.QRect(10, 80, 121, 51))
        self.onkin.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 9pt \"Rockwell\";")
        self.onkin.setObjectName("onkin")
        self.img = QtWidgets.QLabel(parent=Dialog1)
        self.img.setGeometry(QtCore.QRect(270, 10, 121, 81))
        self.img.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img.setObjectName("img")
        self.label_3 = QtWidgets.QLabel(parent=Dialog1)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 181, 171))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\jave_\\OneDrive\\Documentos\\UPIITA\\Prog Avanzada\\Conecct_2\\Conecct\\Gato.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.instrucciones = QtWidgets.QPushButton(parent=Dialog1)
        self.instrucciones.setGeometry(QtCore.QRect(10, 150, 121, 51))
        self.instrucciones.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 9pt \"Rockwell\";")
        self.instrucciones.setObjectName("instrucciones")
        self.label = QtWidgets.QLabel(parent=Dialog1)
        self.label.setGeometry(QtCore.QRect(420, 20, 141, 41))
        self.label.setStyleSheet("font: 14pt \"SWItalc\";\n"
"background-color: rgb(255, 170, 0);")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog1)
        QtCore.QMetaObject.connectSlotsByName(Dialog1)

    def retranslateUi(self, Dialog1):
        _translate = QtCore.QCoreApplication.translate
        Dialog1.setWindowTitle(_translate("Dialog1", "Dialog"))
        self.label_2.setToolTip(_translate("Dialog1", "<html><head/><body><p align=\"center\"><br/>JUGADOR 1</p></body></html>"))
        self.label_2.setText(_translate("Dialog1", "<html><head/><body><p align=\"center\">Jugador</p></body></html>"))
        self.msg.setText(_translate("Dialog1", "    PRESIONE EL BOTON INICIAR KINECT"))
        self.onkin.setText(_translate("Dialog1", "INICIAR KINECT"))
        self.img.setText(_translate("Dialog1", "IMAGEN DE USUARIO"))
        self.instrucciones.setText(_translate("Dialog1", "INSTRUCCIONES"))
        self.label.setText(_translate("Dialog1", "CONNECT 3"))
