# Form implementation generated from reading ui file 'c:\Users\jave_\OneDrive\Documentos\UPIITA\Prog Avanzada\Conecct_2\Conecct\VentanaPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, -10, 721, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\jave_\\OneDrive\\Documentos\\UPIITA\\Prog Avanzada\\Conecct_2\\Conecct\\LOGO FINAL.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 40, 421, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\jave_\\OneDrive\\Documentos\\UPIITA\\Prog Avanzada\\Conecct_2\\Conecct\\No lo planeamos.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-20, 310, 331, 231))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\jave_\\OneDrive\\Documentos\\UPIITA\\Prog Avanzada\\Conecct_2\\Conecct\\ficha amarilla.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 280, 291, 181))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\jave_\\OneDrive\\Documentos\\UPIITA\\Prog Avanzada\\Conecct_2\\Conecct\\ficha roja.png"))
        self.label_4.setObjectName("label_4")
        self.sesion = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sesion.setGeometry(QtCore.QRect(280, 350, 221, 61))
        self.sesion.setStyleSheet("font: 18pt \"Segoe UI\";\n"
"font: 22pt \"Segoe UI\";\n"
"background-color: rgb(255, 0, 0);")
        self.sesion.setObjectName("sesion")
        self.jugar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.jugar.setGeometry(QtCore.QRect(280, 430, 221, 61))
        self.jugar.setStyleSheet("font: 22pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 0);")
        self.jugar.setObjectName("jugar")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 450, 151, 141))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("c:\\Users\\jave_\\OneDrive\\Documentos\\UPIITA\\Prog Avanzada\\Conecct_2\\Conecct\\Perfil.png"))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 745, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuOpciones = QtWidgets.QMenu(parent=self.menuBar)
        self.menuOpciones.setObjectName("menuOpciones")
        MainWindow.setMenuBar(self.menuBar)
        self.Accionconectar = QtGui.QAction(parent=MainWindow)
        self.Accionconectar.setObjectName("Accionconectar")
        self.instrucciones = QtGui.QAction(parent=MainWindow)
        self.instrucciones.setObjectName("instrucciones")
        self.term = QtGui.QAction(parent=MainWindow)
        self.term.setObjectName("term")
        self.menuOpciones.addAction(self.Accionconectar)
        self.menuOpciones.addAction(self.instrucciones)
        self.menuOpciones.addAction(self.term)
        self.menuBar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sesion.setText(_translate("MainWindow", "Iniciar Sesion"))
        self.jugar.setText(_translate("MainWindow", "Jugar"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones"))
        self.Accionconectar.setText(_translate("MainWindow", "Conectar"))
        self.instrucciones.setText(_translate("MainWindow", "Instrucciones"))
        self.term.setText(_translate("MainWindow", "Terminos y Condiciones"))
